project_id = "fkltadvuqdssxrcvhcgl"

[functions.lostark-sibling-characters]
verify_jwt = false

[functions.lostark-character-details]
verify_jwt = false

[functions.main-character-specs]
verify_jwt = false
