export const engravingIconUrlByName: Record<string, string> = {
  각성: '/lostark/engraving/engrave_1255.png',
  강령술: '/lostark/engraving/engrave_1243.png',
  '강화 방패': '/lostark/engraving/engrave_1242.png',
  '결투의 대가': '/lostark/engraving/engrave_1288.png',
  구슬동자: '/lostark/engraving/engrave_1134.png',
  '굳은 의지': '/lostark/engraving/engrave_1123.png',
  '급소 타격': '/lostark/engraving/engrave_1142.png',
  '기습의 대가': '/lostark/engraving/engrave_1249.png',
  긴급구조: '/lostark/engraving/engrave_1302.png',
  '달인의 저력': '/lostark/engraving/engrave_1238.png',
  돌격대장: '/lostark/engraving/engrave_1254.png',
  '마나 효율 증가': '/lostark/engraving/engrave_1168.png',
  '마나의 흐름': '/lostark/engraving/engrave_1251.png',
  바리케이드: '/lostark/engraving/engrave_1253.png',
  '번개의 분노': '/lostark/engraving/engrave_1246.png',
  '부러진 뼈': '/lostark/engraving/engrave_1245.png',
  '분쇄의 주먹': '/lostark/engraving/engrave_1236.png',
  불굴: '/lostark/engraving/engrave_1235.png',
  선수필승: '/lostark/engraving/engrave_1244.png',
  속전속결: '/lostark/engraving/engrave_1300.png',
  '슈퍼 차지': '/lostark/engraving/engrave_1121.png',
  승부사: '/lostark/engraving/engrave_1248.png',
  '시선 집중': '/lostark/engraving/engrave_1298.png',
  실드관통: '/lostark/engraving/engrave_1237.png',
  아드레날린: '/lostark/engraving/engrave_1299.png',
  '안정된 상태': '/lostark/engraving/engrave_1111.png',
  '약자 무시': '/lostark/engraving/engrave_1107.png',
  '에테르 포식자': '/lostark/engraving/engrave_1110.png',
  '여신의 가호': '/lostark/engraving/engrave_1239.png',
  '예리한 둔기': '/lostark/engraving/engrave_1141.png',
  원한: '/lostark/engraving/engrave_1118.png',
  '위기 모면': '/lostark/engraving/engrave_1140.png',
  '저주받은 인형': '/lostark/engraving/engrave_1247.png',
  전문의: '/lostark/engraving/engrave_1301.png',
  '정기 흡수': '/lostark/engraving/engrave_1109.png',
  '정밀 단도': '/lostark/engraving/engrave_1303.png',
  '중갑 착용': '/lostark/engraving/engrave_1240.png',
  '질량 증가': '/lostark/engraving/engrave_1295.png',
  '최대 마나 증가': '/lostark/engraving/engrave_1167.png',
  추진력: '/lostark/engraving/engrave_1296.png',
  '타격의 대가': '/lostark/engraving/engrave_1297.png',
  '탈출의 명수': '/lostark/engraving/engrave_1202.png',
  '폭발물 전문가': '/lostark/engraving/engrave_1241.png',
};
