import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

import '@/assets/reset.scss';
import '@/assets/global.scss';

import Header from '@/components/common/header/Header';

const notoSansKr = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={notoSansKr.variable}>
      <body>
        <Header />

        {children}
      </body>
    </html>
  );
}
